####################################################
## OCTOPENSTACK: Services Architecture Definition ##
####################################################

glance:
  ports: 
    - 9292
    - 4324
  volumes: 
    '/var/log/supervisor': '/var/log/octopenstack/glance'
    #'/etc/glance': '/etc/octopenstack/glance/etc'
  privileged: false


horizon:
  ports:
    - 80
    - 11211 
  volumes:
    '/var/log/supervisor': '/var/log/octopenstack/horizon'
    #'/etc/openstack-dashboard': '/etc/octopenstack/horizon/etc'
  privileged: false


keystone:
  ports:
    - 35357
    - 5000
  volumes:
    '/var/log/supervisor': '/var/log/octopenstack/keystone'
    #'/etc/keystone': '/etc/octopenstack/keystone/etc'
  privileged: false


mysql:
  ports:
    - 3306
  volumes:
    '/var/log/supervisor': '/var/log/octopenstack/mysql'
  privileged: false


nova:
  ports:
    - 8774
    - 8775
  volumes:
    '/var/log/supervisor': '/var/log/octopenstack/nova'
    #'/etc/nova': '/etc/octopenstack/nova/etc'
  privileged: true


rabbitmq:
  ports:
    - 5672
    - 15672
  volumes:
    '/var/log/supervisor': '/var/log/octopenstack/rabbitmq'
    #'/etc/rabbitmq': '/etc/octopenstack/rabbitmq/etc'
  privileged: false
